### ISSUE TITLE
Camera preview instantiation issue

### ISSUE THREAD

**Issue by jamesdeantv** [Bengejd/cordova-plugin-last-cam#4]
Short version: I see no camera preview.

Issue, here is the key word. I say this because I am not receiving any errors from neither Xcode nor web inspector. 

Let me explain a bit what I have encountered while attempting to load your plugin into a blank ionic 4 project.  

Initially, I had errors following the install instructions from the official Ionic documentation. 

The repositories failed to download from the provided links.  

After installing the plugin using the git links you provide in the documentation, I was able to load it into the project.  

Next, I attempted a build, it failed. This was purely an issue with my version of Swift being outdated.   

_As a note for anyone reading this at a later date, be sure to update your Xcode installation to at least 10.1. This will update your Swift installation to the minimum version required, v4.2.  If possible, overwrite your old version of Xcode so the system version will default to Swift v4.2. If not, you will need to manually switch versions._

Once I did this, I was able to compile a build without error.

_Actually, let me back up... There are a few deprecations  in the LastCam.swift file. I will attempt a pull request once I am actually able to get the plugin running in the project._ 

I went a step further and compiled the CameraManager v4.3 into a framework using Carthage and replaced the version included in the libs source of this project.  But, the problem persists.

_Once I load the project.  The camera instantiates with a success result from the startCamera function.  Actually, all of the methods function properly.  However, I see no camera preview._

Any suggestions?

Here is my Ionic info

```
cli packages: (/usr/local/opt/nvm/versions/node/v6.9.2/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 

local packages:

    @ionic/app-scripts : 3.2.1
    Cordova Platforms  : ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.3

System:

    ios-deploy : 2.0.0 
    ios-sim    : 6.1.2 
    Node       : v9.11.2
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 10.1 Build version 10B61 
```

**Comment by Bengejd** [comment]
@jamesdeantv I am looking into this right now. I haven't used this plugin in an Ionic 4 application yet, so it hasn't been updated for it, so it could be a library issue or a change in Ionic 4 that just hasn't been encountered yet. I'll update this when I have more information.

**Comment by Bengejd** [comment]
@jamesdeantv Okay, I have figured out the root causes, which I was delighted to find that it isn't anything in the plugin that is causing it, it's just some changes in Ionic 4.

So to get it to work, I had to change the following:
## Ionic Native
I found out during my initial setup of the ionic 4 project that `ionic-native` was causing a **silent** error in Ionic, even though it wasn't showing up during the compile or running of the app in xCode. To fix this, I found that you have to install **ionic 4 plugins** with `@beta`. So to fix this part:
1. Uninstall `@ionic-native/last-cam`
2. Install ` @ionic-native/last-cam@beta`

3. Now we have to fix the import statement in the **component.ts** file for v4 `ngx`.
`import { LastCam } from '@ionic-native/last-cam/ngx';`

## SCSS
After fixing the `ionic-native` I still wasn't seeing anything in the app, so I re-ran `ionic serve` and realized that the `background-color` attribute was being overwritten. So after some investigation, I found out that we can move the **scss** that we have in the `app.scss` or `global.scss` file into the `component.scss` file, and we have to update the attributes to work with Ionic 4. 
 
#### OLD - app.scss
```
html, body, .ion-app, .ion-content {
  background-color: transparent !important;
}
```

#### NEW - component.scss
```
html, body, ion-app, ion-content {
  --background: transparent !important;
}
```
The biggest changes here are switching from `background-color` to `--background`, and removing the `.class` selectors, for regular ionic component selectors. 

I'm not sure what changes you had to make within the project itself to fix the deprecations and building the cameraManager framework, but I would greatly appreciate that PR if you have the time, since it'll help making updating the project a lot easier for me, and would benefit others. Plus i'd add you to the (currently non-existant) contributors list!

I do think that my original reasoning for not including the Carthage file install, was because it would be an extra, and unnecessary step for users, and might not be that great of user experience. Though I could be wrong, and realize that there is a way to include it without having the user manually install the Cart file.

**Comment by jamesdeantv** [comment]
It appears that you are correct.  It was a styling issue.  I will add that you should also include **.nav-decor**:
```
html, body, ion-app, ion-content, .nav-decor {
  ...
}
```
This is what was obscuring the camera preview.  

I recommend updating the CameraManager library directly from the GitHub repository.  It has the latest fixes for the deprecated syntax changes for Swift 4.2. 

Thanks
